# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64
        distribution: 'adopt'

    - uses: actions/checkout@v2

    - name: Build app
      run: ./mvnw --batch-mode clean install

    - name: Upload yaml schema
      uses: actions/upload-artifact@v2.3.1
      with:
        name: schema.yaml
        path: adoptium-marketplace-schema/target/generated/openapi.yaml
      
    - name: Upload json schema
      uses: actions/upload-artifact@v2.3.1
      with:
        name: schema.json
        path: adoptium-marketplace-schema/target/generated/openapi.json

    - name: Upload example data
      uses: actions/upload-artifact@v2.3.1
      with:
        name: example.json
        path: adoptium-marketplace-schema-tests/src/test/resources/net/adoptium/marketplace/schema/example.json
